(library
 (name kube_api_v1_36)
 (public_name kube.api.v1_36)
 (libraries kube yojson))

(rule
 (alias codegen-check)
 (deps
  ../../codegen/resources-v1.36.2.json
  ../../codegen/openapi/v1.36.2.json
  kube_api_v1_36.ml
  kube_api_v1_36.mli)
 (action
  (run
   %{exe:../../codegen/kube_codegen.exe}
   --schema
   ../../codegen/openapi/v1.36.2.json
   --manifest
   ../../codegen/resources-v1.36.2.json
   --ml
   kube_api_v1_36.ml
   --mli
   kube_api_v1_36.mli
   --check)))
