(library
 (name openapi_codegen)
 (modules openapi_codegen)
 (libraries yojson))

(executable
 (name kube_codegen)
 (modules kube_codegen)
 (libraries openapi_codegen))

(test
 (name test_codegen)
 (modules test_codegen)
 (libraries openapi_codegen alcotest yojson)
 (deps
  fixtures/swagger.json
  fixtures/manifest.json
  fixtures/expected.ml
  fixtures/expected.mli
  fixtures/pruned.json))
