(library
 (name openapi_codegen)
 (modules openapi_codegen)
 (libraries yojson))

(executable
 (name kube_codegen)
 (modules kube_codegen)
 (libraries openapi_codegen))

(test
 (name test_codegen)
 (modules test_codegen)
 (libraries openapi_codegen alcotest yojson)
 (deps
  fixtures/swagger.json
  fixtures/manifest.json
  fixtures/expected.ml
  fixtures/expected.mli
  fixtures/pruned.json))

(rule
 (alias codegen-check)
 (deps
  resources-v1.36.2.json
  openapi/v1.36.2.json
  ../api/v1_36/kube_api_v1_36.ml
  ../api/v1_36/kube_api_v1_36.mli)
 (action
  (run
   %{exe:kube_codegen.exe}
   --schema
   openapi/v1.36.2.json
   --manifest
   resources-v1.36.2.json
   --ml
   ../api/v1_36/kube_api_v1_36.ml
   --mli
   ../api/v1_36/kube_api_v1_36.mli
   --check)))
