(library
 (name kube)
 (public_name kube)
 (private_modules clock crypto_runtime spdy spdy_zlib yaml_lite)
 (foreign_stubs
  (language c)
  (names clock_stubs spdy_zlib_stubs))
 (c_library_flags -lz)
 (libraries
  unix
  threads.posix
  base64
  ca-certs
  domain-name
  ipaddr
  mirage-crypto-rng.unix
  ptime.clock.os
  secret
  secret.unix
  tls.unix
  uri
  x509
  yojson))
