(** Generated by ocaml-k8s from Kubernetes v1.99.0 OpenAPI v2.
    Source: https://example.invalid/kubernetes/swagger.json
    Upstream SHA-256: fixture-sha256
    Definitions in dependency closure: 4.
    Do not edit by hand. *)

type int_or_string = [ `Int of int32 | `String of string ]

type example_v1_widget = {
  api_version : string option;
  kind : string option;
  metadata : io_k8s_apimachinery_pkg_apis_meta_v1_object_meta option;
  spec : example_v1_widget_spec;
}
and example_v1_widget_spec = {
  image : string;
  ports : (io_k8s_apimachinery_pkg_util_intstr_int_or_string) list option;
  replicas : int32 option;
}
and io_k8s_apimachinery_pkg_apis_meta_v1_object_meta = {
  generation : int64 option;
  labels : (string * (string)) list option;
  name : string option;
  namespace : string option;
  resource_version : string option;
}
and io_k8s_apimachinery_pkg_util_intstr_int_or_string = int_or_string

let make_example_v1_widget ?api_version ?kind ?metadata ~spec () : example_v1_widget =
  {
    api_version;
    kind;
    metadata;
    spec;
  }

let make_example_v1_widget_spec ~image ?ports ?replicas () : example_v1_widget_spec =
  {
    image;
    ports;
    replicas;
  }

let make_io_k8s_apimachinery_pkg_apis_meta_v1_object_meta ?generation ?labels ?name ?namespace ?resource_version () : io_k8s_apimachinery_pkg_apis_meta_v1_object_meta =
  {
    generation;
    labels;
    name;
    namespace;
    resource_version;
  }

let ( let* ) result fn =
  match result with Ok value -> fn value | Error _ as error -> error

let with_context context = function
  | Ok value -> Ok value
  | Error message -> Error (context ^ ": " ^ message)

let decode_string = function
  | `String value -> Ok value
  | _ -> Error "expected string"

let decode_bool = function
  | `Bool value -> Ok value
  | _ -> Error "expected boolean"

let integer_literal = function
  | `Int value -> Some (string_of_int value)
  | `Intlit value -> Some value
  | _ -> None

let decode_int json =
  match integer_literal json with
  | Some value -> (
      match int_of_string_opt value with
      | Some value -> Ok value
      | None -> Error "integer is outside the OCaml int range")
  | None -> Error "expected integer"

let decode_int32 json =
  match integer_literal json with
  | Some value -> (
      try Ok (Int32.of_string value)
      with Failure _ -> Error "integer is outside the int32 range")
  | None -> Error "expected int32"

let decode_int64 json =
  match integer_literal json with
  | Some value -> (
      try Ok (Int64.of_string value)
      with Failure _ -> Error "integer is outside the int64 range")
  | None -> Error "expected int64"

let decode_float = function
  | `Float value -> Ok value
  | `Int value -> Ok (float_of_int value)
  | `Intlit value -> (
      try Ok (float_of_string value) with Failure _ -> Error "invalid number")
  | _ -> Error "expected number"

let decode_int_or_string = function
  | `String value -> Ok (`String value)
  | (`Int _ | `Intlit _) as json ->
      let* value = decode_int32 json in
      Ok (`Int value)
  | _ -> Error "expected int32 or string"

let encode_int_or_string = function
  | `String value -> `String value
  | `Int value -> `Intlit (Int32.to_string value)

let decode_list decode = function
  | `List values ->
      let rec loop index accumulator = function
        | [] -> Ok (List.rev accumulator)
        | value :: rest ->
            let* value = with_context (Printf.sprintf "item %d" index) (decode value) in
            loop (index + 1) (value :: accumulator) rest
      in
      loop 0 [] values
  | _ -> Error "expected array"

let decode_map decode = function
  | `Assoc fields ->
      let rec loop accumulator = function
        | [] -> Ok (List.rev accumulator)
        | (name, json) :: rest ->
            let* value = with_context name (decode json) in
            loop ((name, value) :: accumulator) rest
      in
      loop [] fields
  | _ -> Error "expected object"

let optional_field name decode fields =
  match List.assoc_opt name fields with
  | None | Some `Null -> Ok None
  | Some json ->
      let* value = with_context name (decode json) in
      Ok (Some value)

let required_field name decode fields =
  match List.assoc_opt name fields with
  | None -> Error (name ^ ": required field is missing")
  | Some `Null -> Error (name ^ ": required field is null")
  | Some json -> with_context name (decode json)

let optional_json name encode = function
  | None -> None
  | Some value -> Some (name, encode value)

let () =
  ignore decode_int;
  ignore decode_float

let metadata_of_resource_json json =
  match Kube.Core.object_meta_of_json json with
  | Ok metadata -> metadata
  | Error _ ->
      let json =
        match json with
        | `Assoc fields ->
            let metadata =
              match List.assoc_opt "metadata" fields with
              | Some (`Assoc metadata) ->
                  if List.mem_assoc "name" metadata then `Assoc metadata
                  else `Assoc (("name", `String "") :: metadata)
              | _ -> `Assoc [ ("name", `String "") ]
            in
            `Assoc (("metadata", metadata) :: List.remove_assoc "metadata" fields)
        | _ -> `Assoc [ ("metadata", `Assoc [ ("name", `String "") ]) ]
      in
      match Kube.Core.object_meta_of_json json with
      | Ok metadata -> metadata
      | Error message -> invalid_arg ("generated resource metadata: " ^ message)

let rec example_v1_widget_of_json (json : Yojson.Safe.t) : (example_v1_widget, string) result =
  match json with
  | `Assoc fields ->
      let* api_version = optional_field "apiVersion" (fun json -> decode_string json) fields in
      let* kind = optional_field "kind" (fun json -> decode_string json) fields in
      let* metadata = optional_field "metadata" (fun json -> io_k8s_apimachinery_pkg_apis_meta_v1_object_meta_of_json json) fields in
      let* spec = required_field "spec" (fun json -> example_v1_widget_spec_of_json json) fields in
      Ok
        ({
          api_version;
          kind;
          metadata;
          spec;
        } : example_v1_widget)
  | _ -> Error "example.v1.Widget must be an object"
and example_v1_widget_to_json (value : example_v1_widget) : Yojson.Safe.t =
  `Assoc
    (List.filter_map Fun.id
      [
        optional_json "apiVersion" (fun value -> `String value) value.api_version;
        optional_json "kind" (fun value -> `String value) value.kind;
        optional_json "metadata" (fun value -> io_k8s_apimachinery_pkg_apis_meta_v1_object_meta_to_json value) value.metadata;
        Some ("spec", example_v1_widget_spec_to_json value.spec);
      ])
and example_v1_widget_spec_of_json (json : Yojson.Safe.t) : (example_v1_widget_spec, string) result =
  match json with
  | `Assoc fields ->
      let* image = required_field "image" (fun json -> decode_string json) fields in
      let* ports = optional_field "ports" (fun json -> decode_list (fun json -> io_k8s_apimachinery_pkg_util_intstr_int_or_string_of_json json) json) fields in
      let* replicas = optional_field "replicas" (fun json -> decode_int32 json) fields in
      Ok
        ({
          image;
          ports;
          replicas;
        } : example_v1_widget_spec)
  | _ -> Error "example.v1.WidgetSpec must be an object"
and example_v1_widget_spec_to_json (value : example_v1_widget_spec) : Yojson.Safe.t =
  `Assoc
    (List.filter_map Fun.id
      [
        Some ("image", `String value.image);
        optional_json "ports" (fun value -> `List (List.map (fun value -> io_k8s_apimachinery_pkg_util_intstr_int_or_string_to_json value) value)) value.ports;
        optional_json "replicas" (fun value -> `Intlit (Int32.to_string value)) value.replicas;
      ])
and io_k8s_apimachinery_pkg_apis_meta_v1_object_meta_of_json (json : Yojson.Safe.t) : (io_k8s_apimachinery_pkg_apis_meta_v1_object_meta, string) result =
  match json with
  | `Assoc fields ->
      let* generation = optional_field "generation" (fun json -> decode_int64 json) fields in
      let* labels = optional_field "labels" (fun json -> decode_map (fun json -> decode_string json) json) fields in
      let* name = optional_field "name" (fun json -> decode_string json) fields in
      let* namespace = optional_field "namespace" (fun json -> decode_string json) fields in
      let* resource_version = optional_field "resourceVersion" (fun json -> decode_string json) fields in
      Ok
        ({
          generation;
          labels;
          name;
          namespace;
          resource_version;
        } : io_k8s_apimachinery_pkg_apis_meta_v1_object_meta)
  | _ -> Error "io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta must be an object"
and io_k8s_apimachinery_pkg_apis_meta_v1_object_meta_to_json (value : io_k8s_apimachinery_pkg_apis_meta_v1_object_meta) : Yojson.Safe.t =
  `Assoc
    (List.filter_map Fun.id
      [
        optional_json "generation" (fun value -> `Intlit (Int64.to_string value)) value.generation;
        optional_json "labels" (fun value -> `Assoc (List.map (fun (name, value) -> (name, `String value)) value)) value.labels;
        optional_json "name" (fun value -> `String value) value.name;
        optional_json "namespace" (fun value -> `String value) value.namespace;
        optional_json "resourceVersion" (fun value -> `String value) value.resource_version;
      ])
and io_k8s_apimachinery_pkg_util_intstr_int_or_string_of_json (json : Yojson.Safe.t) : (io_k8s_apimachinery_pkg_util_intstr_int_or_string, string) result = decode_int_or_string json
and io_k8s_apimachinery_pkg_util_intstr_int_or_string_to_json (value : io_k8s_apimachinery_pkg_util_intstr_int_or_string) : Yojson.Safe.t = encode_int_or_string value

module Meta_v1 = struct
  module ObjectMeta = struct
    type nonrec t = io_k8s_apimachinery_pkg_apis_meta_v1_object_meta
    let make = make_io_k8s_apimachinery_pkg_apis_meta_v1_object_meta
    let of_json = io_k8s_apimachinery_pkg_apis_meta_v1_object_meta_of_json
    let to_json = io_k8s_apimachinery_pkg_apis_meta_v1_object_meta_to_json
  end
end

module Int_or_string = struct
  type nonrec t = int_or_string
  let of_int32 value = `Int value
  let of_string value = `String value
  let of_json = io_k8s_apimachinery_pkg_util_intstr_int_or_string_of_json
  let to_json = io_k8s_apimachinery_pkg_util_intstr_int_or_string_to_json
end

module Example_v1 = struct
  module Widget = struct
    type nonrec t = example_v1_widget
    let make = make_example_v1_widget
    let api =
      {
        Kube.Core.group = "example.dev";
        version = "v1";
        kind = "Widget";
        plural = "widgets";
        scope = Kube.Core.Namespaced;
      }
    let metadata value =
      metadata_of_resource_json (example_v1_widget_to_json value)
    let of_json = example_v1_widget_of_json
    let to_json = example_v1_widget_to_json
  end
end

let all_resources =
  [
    Example_v1.Widget.api;
  ]
