(** Generated by ocaml-k8s from Kubernetes v1.99.0 OpenAPI v2.
    Source: https://example.invalid/kubernetes/swagger.json
    Upstream SHA-256: fixture-sha256
    Definitions in dependency closure: 4.
    Do not edit by hand. *)

type int_or_string = [ `Int of int32 | `String of string ]

type example_v1_widget = {
  api_version : string option;
  kind : string option;
  metadata : io_k8s_apimachinery_pkg_apis_meta_v1_object_meta option;
  spec : example_v1_widget_spec;
}
and example_v1_widget_spec = {
  image : string;
  ports : (io_k8s_apimachinery_pkg_util_intstr_int_or_string) list option;
  replicas : int32 option;
}
and io_k8s_apimachinery_pkg_apis_meta_v1_object_meta = {
  generation : int64 option;
  labels : (string * (string)) list option;
  name : string option;
  namespace : string option;
  resource_version : string option;
}
and io_k8s_apimachinery_pkg_util_intstr_int_or_string = int_or_string

val make_example_v1_widget : ?api_version:string -> ?kind:string -> ?metadata:io_k8s_apimachinery_pkg_apis_meta_v1_object_meta -> spec:example_v1_widget_spec -> unit -> example_v1_widget
val make_example_v1_widget_spec : image:string -> ?ports:(io_k8s_apimachinery_pkg_util_intstr_int_or_string) list -> ?replicas:int32 -> unit -> example_v1_widget_spec
val make_io_k8s_apimachinery_pkg_apis_meta_v1_object_meta : ?generation:int64 -> ?labels:(string * (string)) list -> ?name:string -> ?namespace:string -> ?resource_version:string -> unit -> io_k8s_apimachinery_pkg_apis_meta_v1_object_meta

val example_v1_widget_of_json : Yojson.Safe.t -> (example_v1_widget, string) result
val example_v1_widget_to_json : example_v1_widget -> Yojson.Safe.t
val example_v1_widget_spec_of_json : Yojson.Safe.t -> (example_v1_widget_spec, string) result
val example_v1_widget_spec_to_json : example_v1_widget_spec -> Yojson.Safe.t
val io_k8s_apimachinery_pkg_apis_meta_v1_object_meta_of_json : Yojson.Safe.t -> (io_k8s_apimachinery_pkg_apis_meta_v1_object_meta, string) result
val io_k8s_apimachinery_pkg_apis_meta_v1_object_meta_to_json : io_k8s_apimachinery_pkg_apis_meta_v1_object_meta -> Yojson.Safe.t
val io_k8s_apimachinery_pkg_util_intstr_int_or_string_of_json : Yojson.Safe.t -> (io_k8s_apimachinery_pkg_util_intstr_int_or_string, string) result
val io_k8s_apimachinery_pkg_util_intstr_int_or_string_to_json : io_k8s_apimachinery_pkg_util_intstr_int_or_string -> Yojson.Safe.t

module Meta_v1 : sig
  module ObjectMeta : sig
    type t = io_k8s_apimachinery_pkg_apis_meta_v1_object_meta
    val make : ?generation:int64 -> ?labels:(string * (string)) list -> ?name:string -> ?namespace:string -> ?resource_version:string -> unit -> t
    val of_json : Yojson.Safe.t -> (t, string) result
    val to_json : t -> Yojson.Safe.t
  end
end

module Int_or_string : sig
  type t = int_or_string
  val of_int32 : int32 -> t
  val of_string : string -> t
  val of_json : Yojson.Safe.t -> (t, string) result
  val to_json : t -> Yojson.Safe.t
end

module Example_v1 : sig
  module Widget : sig
    type t = example_v1_widget
    val make : ?api_version:string -> ?kind:string -> ?metadata:io_k8s_apimachinery_pkg_apis_meta_v1_object_meta -> spec:example_v1_widget_spec -> unit -> t
    include Kube.Core.Resource with type t := t
  end
end

val all_resources : Kube.Core.api list
